const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Pins the Gradle daemon to JDK 17.
 *
 * Expo SDK 57 / React Native 0.86 build against JDK 17. When the daemon runs on
 * a newer JDK, AGP launches the prefab CLI under that JVM and prefab emits the
 * JEP 472 restricted-method banner on stderr. AGP turns any prefab stderr into a
 * hard failure, which surfaces with no underlying CMake error to point at:
 *
 *   Execution failed for task ':react-native-worklets:configureCMakeDebug[x86_64]'.
 *   > WARNING: A restricted method in java.lang.System has been called
 *
 * Gradle's updateDaemonJvm task (Android Studio runs it) writes this file
 * pinning whatever JDK is current, which is how the daemon ended up on 25.
 * android/ is gitignored and regenerated by prebuild, so the pin is reapplied
 * here on every prebuild rather than edited by hand.
 */
const TOOLCHAIN_VERSION = '17';

const withGradleDaemonJvm = (config) =>
  withDangerousMod(config, [
    'android',
    async (config) => {
      const gradleDir = path.join(config.modRequest.platformProjectRoot, 'gradle');
      const filePath = path.join(gradleDir, 'gradle-daemon-jvm.properties');

      await fs.promises.mkdir(gradleDir, { recursive: true });
      await fs.promises.writeFile(
        filePath,
        [
          '# Generated by the withGradleDaemonJvm config plugin. Do not edit by hand.',
          '# Do not run Gradle\'s updateDaemonJvm task: a newer JDK breaks the AGP prefab step.',
          `toolchainVersion=${TOOLCHAIN_VERSION}`,
          '',
        ].join('\n'),
        'utf8'
      );

      return config;
    },
  ]);

module.exports = withGradleDaemonJvm;
